version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-events
    restart: always
    environment:
      POSTGRES_USER: wp
      POSTGRES_PASSWORD: wp123
      POSTGRES_DB: events
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    driver: local
